extern void irq0();
extern void irq1();   
extern void irq13();   
extern void irq14();             
extern void irq15();
void irq_uninstall_handler(int irq);
void irq_install_handler(int irq, void (*handler)(struct regs *r));
void irq_remap(void);
void irq_install();
void irq_handler(struct regs *r);